appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: JpNKaZmq1ESm0oPepGQhrDQTTE35cM1ULwuVgicdfIEVqVnaEk3sSFuv9LDoClEeRPh+SdwggsRDY9BULHn+kID0gQFYCHmfMpaG7ZyjUTmHrdFtxgc3kVN4BXSUDan3eEZBIdF1muvQCdIAiPdzXfMqItU2GkN0/mDuQHjOXDvsZ962eZSJxyuh+0CXQjL3wE1ckRw3yD22kPSt3sFvGEmJ9gTUIcyDfXsua1FdUgoef/z27/9seB7QcOVkubt+zXdF8ngCZpI79Dd5cIa1brSA+bOUNg/dOI0kHm1IHItIyoEGhrf/zYsrL9a4gPpua8HNGlNmVh0JmbhcVl2LeO6axuXPP2Ge0rb7MEkLkZwb0DAcqI/Moe9n/0uq50/SQSMV9SNRt4+XqGYjSfZRJtUUh1AnNck534Wi6ZaF+BY0z6EAXBJHm14sXYyLsb6bSTb2eCGUfJCBkVShBNuz8UxU3Q/G24Wh7/rSwXqXyw0f9858f7JVTAVPZ34+pLKQV5cgdRxU4ZGDkHMFqVj1J1oeBK+Brw+Cu4ZpqtajSRZXGBz5O8Lg5hIfgMH1g8ZXf5TJ0b1Pctu4k5GJqUgN7qCBjt1WC6D3r2ZEYH+IOHFC4X5OUN/hz6Yo2ysoRymBJDDz8nDE3YHLb4v1+mPHE+8TNxzsvJPCz3cgVqXHYUY=
