travis:
  secure:
    BINSTAR_TOKEN: q0Gthgl+bgmSS8Hjw1pdAbbHKkyOrBCWqohHtvxKhY9u9e3ExCvl4Q7uo5YItRLQxf0MKNMghxrcmoVnCcKTgZBsGRWh6xiyUqeAOW/CDXII3MjEHRRdEx5jKR4cDzNB6Gql90beVrB1SN0FlbTDrxOZxNkm6aj0zUmSowwr4bEQ/B3uDHH0Oiv1GVXjyAuRjX5eQDq01H0uTCqMfh1G28tojJVwPvgtITM8JeUSZqP9U0TWu1jt0PilRG7wlAE5oi14UdBjM8zJQuurmoJJ+Gg/uoPwlFW8pbUCvqcnMa/FDMfR6MRkYYg7MzWYjsnX2jWzn9OTHlHFHLwc/CAxC7vVyC5c80JJbWBOIUVvL9ueISQz6fhS8gCMWvygEE5y7qxHwrn+xVh3PKoAg3/p2A+2PN6LMuS7/kOJdGXj74UHkHWU8UMvDodVwQ7Yl6B1KU8FPwkTZjavRkFgwDt2dtoNrtaY7OAMn/x/m4eI2ccn+HEFZhMp6V39ofkyaR0yTuzq5qzmUXk6krYFJCH6g3reOcbeuCE9T1CY8E8D79jjqrXahv99XYKjSxElRIqlsP2RlY9bJ55xSqFsZX/9cW9DsNV68MxsGzh8j1um/knTBOxQXtOXk0aQYPUodD5BIg4h57fFBPEYDsShOws1vaQibuYSoM4gSJfKfZEnm1k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
